import { Hero } from './hero';

export const HEROES: Hero[] = [
    {name: "Alex", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Alex.png", id: 31, party: false, ally1: "Deborah", ally2: "Tao", ally3: "Belle"},
    {name: "Alfred", property: "Rock", type: "AreaAttack", terr1: "Grass", imgurl: "../assets/Alfred.png", id: 6, party: false, ally1: "Sraka", ally2: "Lilid", ally3: "Shark"},
    {name: "Angela", property: "Paper", type: "Balance", terr1: "Poison", imgurl: "../assets/Angela.png", id: 60, party: false, ally1: "Jenny", ally2: "Jin", ally3: "Lena"},
    {name: "Aran", property: "Rock", type: "Balance", terr1: "Thornbush", imgurl: "../assets/Aran.png", id: 63, party: false, ally1: "Evan", ally2: "Eunwol", ally3: "Mercedes"},
    {name: "Azrael", property: "Paper", type: "Attack", terr1: "Thornbush", imgurl: "../assets/Azrael.png", id: 68, party: false, ally1: "Chris", ally2: "Angela", ally3: "Lena"},
    {name: "Banshee", property: "Scissors", type: "Balance", terr1: "Poison", imgurl: "../assets/Banshee.png", id: 40, party: false, ally1: "Spooky", ally2: "Spooky", ally3: "Spooky"},
    {name: "Bearman", property: "Scissors", type: "Defense", terr1: "Poison", imgurl: "../assets/Bearman.png", id: 28, party: false, ally1: "Carrot", ally2: "Chenny", ally3: "Shu-Shu"},
    {name: "Belle", property: "Scissors", type: "Support", terr1: "Swamp", imgurl: "../assets/Belle.png", id: 55, party: false, ally1: "Dolores", ally2: "Hella", ally3: "Nirvana"},
    {name: "Camelia", property: "Paper", type: "Support", terr1: "Thornbush", imgurl: "../assets/Camelia.png", id: 76, party: false, ally1: "Ian", ally2: "Sraka", ally3: "Krut"},
    {name: "Carrot", property: "Paper", type: "Attack", terr1: "Grass", imgurl: "../assets/Carrot.png", id: 3, party: false, ally1: "Jenny", ally2: "Serendi", ally3: "Kitty"},
    {name: "Cat Sidhe", property: "Rock", type: "Attack", terr1: "Thornbush", imgurl: "../assets/Cat_Sidhe.png", id: 64, party: false, ally1: "Ian", ally2: "Mas", ally3: "Lena"},
    {name: "Celestial", property: "Paper", type: "Support", terr1: "Grass", imgurl: "../assets/Celestial.png", id: 50, party: false, ally1: "Yekaterina", ally2: "Angela", ally3: "Lily"},
    {name: "Chenny", property: "Scissors", type: "Balance", terr1: "Glacier", imgurl: "../assets/Chenny.png", id: 42, party: false, ally1: "Alfred", ally2: "Deborah", ally3: "Klein"},
    {name: "Chris", property: "Paper", type: "Defense", terr1: "Grass", imgurl: "../assets/Chris.png", id: 16, party: false, ally1: "Lily", ally2: "Jin", ally3: "Unknown"},
    {name: "Cleo", property: "Paper", type: "Balance", terr1: "Thornbush", imgurl: "../assets/Cleo.png", id: 26, party: false, ally1: "Carrot", ally2: "Chenny", ally3: "Shu-Shu"},
    {name: "Deborah", property: "Scissors", type: "AreaAttack", terr1: "Poison", imgurl: "../assets/Deborah.png", id: 4, party: false, ally1: "Alfred", ally2: "Lance", ally3: "Klein"},
    {name: "Deimos", property: "Scissors", type: "Defense", terr1: "Poison", imgurl: "../assets/Deimos.png", id: 59, party: false, ally1: "Carrot", ally2: "Lily", ally3: "Valkyrie"},
    {name: "Dolores", property: "Paper", type: "Balance", terr1: "Lava", imgurl: "../assets/Dolores.png", id: 17, party: false, ally1: "Kai", ally2: "Rage", ally3: "Fruel"},
    {name: "Dominique", property: "Rock", type: "Attack", terr1: "Thornbush", imgurl: "../assets/Dominique.png", id: 23, party: false, ally1: "Henry", ally2: "Lily", ally3: "Angela"},
    {name: "Elektra", property: "Scissors", type: "Support", terr1: "Thornbush", imgurl: "../assets/Elektra.png", id: 54, party: false, ally1: "Ian", ally2: "Carrot", ally3: "Kitty"},
    {name: "Evan", property: "Scissors", type: "AreaAttack", terr1: "Lava", imgurl: "../assets/Evan.png", id: 57, party: false, ally1: "Mercedes", ally2: "Phantom", ally3: "Luminous"},
    {name: "Frankenstein", property: "Scissors", type: "Attack", terr1: "Poison", imgurl: "../assets/Frankenstein.png", id: 24, party: false, ally1: "Seira", ally2: "Alfred", ally3: "Raskreia"},
    {name: "Fruel", property: "Scissors", type: "Attack", terr1: "Thornbush", imgurl: "../assets/Fruel.png", id: 48, party: false, ally1: "Lily", ally2: "Azrael", ally3: "Nirvana"},
    {name: "Gillan", property: "Rock", type: "Support", terr1: "Poison", imgurl: "../assets/Gillan.png", id: 19, party: false, ally1: "Henry", ally2: "Muang", ally3: "Zero"},
    {name: "Henry", property: "Rock", type: "Attack", terr1: "Swamp", imgurl: "../assets/Henry.png", id: 34, party: false, ally1: "Dominique", ally2: "Angela", ally3: "Lily"},
    {name: "Hongyeom", property: "Rock", type: "AreaAttack", terr1: "Lava", imgurl: "../assets/hongyeom.png", id: 72, party: false, ally1: "Mas", ally2: "Lena", ally3: "Sonic_Boom"},
    {name: "Ian", property: "Rock", type: "Balance", terr1: "Thornbush", imgurl: "../assets/Ian.png", id: 9, party: false, ally1: "Serendi", ally2: "Jin", ally3: "Chenny"},
    {name: "Ildo", property: "Paper", type: "Defense", terr1: "Thornbush", imgurl: "../assets/Ildo.png", id: 71, party: false, ally1: "Hongyeom", ally2: "Ian", ally3: "Taehwa"},
    {name: "Jack", property: "Rock", type: "Defense", terr1: "Lava", imgurl: "../assets/Jack.png", id: 12, party: false, ally1: "Lance", ally2: "Mas", ally3: "Shu-Shu"},
    {name: "Jenny", property: "Paper", type: "AreaAttack", terr1: "Thornbush", imgurl: "../assets/Jenny.png", id: 18, party: false, ally1: "Carrot", ally2: "Rage", ally3: "Momo"},
    {name: "Jin", property: "Scissors", type: "Attack", terr1: "Lava", imgurl: "../assets/Jin.png", id: 20, party: false, ally1: "Kai", ally2: "Rage", ally3: "Unknown"},
    {name: "Kai", property: "Rock", type: "Balance", terr1: "Lava", imgurl: "../assets/Kai.png", id: 5, party: false, ally1: "Chris", ally2: "Raboff", ally3: "Mu"},
    {name: "Kitty", property: "Rock", type: "AreaAttack", terr1: "Glacier", imgurl: "../assets/Kitty.png", id: 32, party: false, ally1: "Sraka", ally2: "Dolores", ally3: "Moa"},
    {name: "Klein", property: "Paper", type: "AreaAttack", terr1: "Lava", imgurl: "../assets/Klein.png", id: 69, party: false, ally1: "Ian", ally2: "Jack", ally3: "Bearman"},
    {name: "Krut", property: "Rock", type: "Attack", terr1: "Lava", imgurl: "../assets/Krut.png", id: 43, party: false, ally1: "Sraka", ally2: "Lily", ally3: "Jin"},
    {name: "Ky Kiske", property: "Paper", type: "Balance", terr1: "Glacier", imgurl: "../assets/Ky_Kiske.png", id: 79, party: false, ally1: "Sol_Badguy", ally2: "May", ally3: "Ramlethal"},
    {name: "Lance", property: "Scissors", type: "Defense", terr1: "Swamp", imgurl: "../assets/Lance.png", id: 7, party: false, ally1: "Alfred", ally2: "Deborah", ally3: "Klein"},
    {name: "Lee", property: "Scissors", type: "Attack", terr1: "Glacier", imgurl: "../assets/Lee.png", id: 67, party: false, ally1: "Moa", ally2: "Elektra", ally3: "Klein"},
    {name: "Lena", property: "Scissors", type: "Balance", terr1: "Glacier", imgurl: "../assets/Lena.png", id: 44, party: false, ally1: "Nox", ally2: "Persona", ally3: "Fruel"},
    {name: "Lilid", property: "Rock", type: "Defense", terr1: "Poison", imgurl: "../assets/Lilid.png", id: 30, party: false, ally1: "Ian", ally2: "Poni", ally3: "Jack"},
    {name: "Lily", property: "Paper", type: "Attack", terr1: "Swamp", imgurl: "../assets/Lily.png", id: 21, party: false, ally1: "Henry", ally2: "Dominique", ally3: "Angela"},
    {name: "Lucas", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Lucas.png", id: 49, party: false, ally1: "Jack", ally2: "Ian", ally3: "Poni"},
    {name: "Luminous", property: "Scissors", type: "Support", terr1: "Glacier", imgurl: "../assets/Luminous.png", id: 62, party: false, ally1: "Aran", ally2: "Eunwol", ally3: "Phantom"},
    {name: "Mas", property: "Paper", type: "Support", terr1: "Grass", imgurl: "../assets/Mas.png", id: 8, party: false, ally1: "Serendi", ally2: "Nox", ally3: "Fruel"},
    {name: "May", property: "Scissors", type: "Attack", terr1: "Water", imgurl: "../assets/May.png", id: 78, party: false, ally1: "Sol_Badguy", ally2: "Ky_Kiske", ally3: "Ramlethal"},
    {name: "Mercedes", property: "Rock", type: "Attack", terr1: "Grass", imgurl: "../assets/Mercedes.png", id: 58, party: false, ally1: "Evan", ally2: "Phantom", ally3: "Luminous"},
    {name: "Moa", property: "Paper", type: "AreaAttack", terr1: "Lava", imgurl: "../assets/Moa.png", id: 29, party: false, ally1: "Elektra", ally2: "Lee", ally3: "Klein"},
    {name: "Momo", property: "Rock", type: "Attack", terr1: "Grass", imgurl: "../assets/Momo.png", id: 1, party: false, ally1: "Bearman", ally2: "Muang", ally3: "Alex"},
    {name: "Mu", property: "Paper", type: "Balance", terr1: "Swamp", imgurl: "../assets/Mu.png", id: 2, party: false, ally1: "Dolores", ally2: "Persona", ally3: "Tao"},
    {name: "Muzaka", property: "Rock", type: "Defense", terr1: "Thornbush", imgurl: "../assets/Muzaka.png", id: 75, party: false, ally1: "Kai", ally2: "Sonic_Boom", ally3: "Poni"},
    {name: "Muang", property: "Scissors", type: "AreaAttack", terr1: "Lava", imgurl: "../assets/Muang.png", id: 37, party: false, ally1: "Jack", ally2: "Seira", ally3: "Raskreia"},
    {name: "Nirvana", property: "Paper", type: "Support", terr1: "Water", imgurl: "../assets/Nirvana.png", id: 47, party: false, ally1: "Hella", ally2: "Sione", ally3: "Belle"},
    {name: "Noel", property: "Rock", type: "Attack", terr1: "Grass", imgurl: "../assets/Noel.png", id: 52, party: false, ally1: "Ragna", ally2: "Jin_Kisaragi", ally3: "Rachel"},
    {name: "Nox", property: "Paper", type: "Attack", terr1: "Glacier", imgurl: "../assets/Nox.png", id: 45, party: false, ally1: "Bearman", ally2: "Elektra", ally3: "Momo"},
    {name: "Parsifal", property: "Scissors", type: "Attack", terr1: "Water", imgurl: "../assets/Parsifal.png", id: 77, party: false, ally1: "Deimos", ally2: "Valkyrie", ally3: "Chris"},
    {name: "Persona", property: "Rock", type: "Balance", terr1: "Water", imgurl: "../assets/Persona.png", id: 33, party: false, ally1: "Sonic_Boom", ally2: "Lena", ally3: "Shark"},
    {name: "Phantom", property: "Paper", type: "Balance", terr1: "Thornbush", imgurl: "../assets/Phantom.png", id: 56, party: false, ally1: "Evan", ally2: "Mercedes", ally3: "Luminous"},
    {name: "Poni", property: "Scissors", type: "Balance", terr1: "Lava", imgurl: "../assets/Poni.png", id: 13, party: false, ally1: "Ian", ally2: "Dolores", ally3: "Moa"},
    {name: "Raboff", property: "Paper", type: "Defense", terr1: "Grass", imgurl: "../assets/Raboff.png", id: 22, party: false, ally1: "Chris", ally2: "Alex", ally3: "Mu"},
    {name: "Rachel", property: "Paper", type: "AreaAttack", terr1: "Poison", imgurl: "../assets/Rachel_Alucard.png", id: 53, party: false, ally1: "Ragna", ally2: "Jin Kisaragi", ally3: "Noel"},
    {name: "Rage", property: "Rock", type: "Attack", terr1: "Poison", imgurl: "../assets/Rage.png", id: 14, party: false, ally1: "Chris", ally2: "Serendi", ally3: "Dominique"},
    {name: "Ragna", property: "Scissors", type: "Attack", terr1: "Lava", imgurl: "../assets/Ragna.png", id: 51, party: false, ally1: "Jin_Kisaragi", ally2: "Noel", ally3: "Rachel"},
    {name: "Raizel", property: "Paper", type: "Attack", terr1: "Swamp", imgurl: "../assets/Raizel.png", id: 79, party: false, ally1: "Frankenstein", ally2: "Seira", ally3: "Unknown"},
    {name: "Ramlethal", property: "Scissors", type: "AreaAttack", terr1: "Thornbush", imgurl: "../assets/Ramlethal_Valentine.png", id: 77, party: false, ally1: "Ky_Kiske", ally2: "Sol_Badguy", ally3: "May"},
    {name: "Raskreia", property: "Scissors", type: "AreaAttack", terr1: "Grass", imgurl: "../assets/Raskreia.png", id: 25, party: false, ally1: "Seira", ally2: "Frankenstein", ally3: "Nox"},
    {name: "Reina", property: "Scissors", type: "Balance", terr1: "Grass", imgurl: "../assets/Reina.png", id: 61, party: false, ally1: "Jin", ally2: "Lily", ally3: "Belle"},
    {name: "Ryeogang", property: "Paper", type: "Balance", terr1: "Water", imgurl: "../assets/Ryeogang.png", id: 78, party: false, ally1: "Carrot", ally2: "Chenny", ally3: "Shu-Shu"},
    {name: "Seira", property: "Scissors", type: "Attack", terr1: "Glacier", imgurl: "../assets/Seira.png", id: 76, party: false, ally1: "Raskreia", ally2: "Frankenstein", ally3: "Lily"},
    {name: "Serendi", property: "Rock", type: "Balance", terr1: "Water", imgurl: "../assets/Serendi.png", id: 15, party: false, ally1: "Ian", ally2: "Moa", ally3: "Momo"},
    {name: "Serphina", property: "Scissors", type: "AreaAttack", terr1: "Swamp", imgurl: "../assets/serphina.png", id: 65, party: false, ally1: "Mas", ally2: "Fruel", ally3: "Persona"},
    {name: "Shark", property: "Scissors", type: "Balance", terr1: "Water", imgurl: "../assets/Shark.png", id: 36, party: false, ally1: "Deborah", ally2: "Cleo", ally3: "Hella"},
    {name: "Shu-Shu", property: "Rock", type: "Support", terr1: "Water",  imgurl: "../assets/Shu-Shu.png", id: 39, party: false, ally1: "Gillan", ally2: "Alfred", ally3: "Zero"},
    {name: "Sione", property: "Scissors", type: "Attack", terr1: "Swamp", imgurl: "../assets/Sione.png", id: 70, party: false, ally1: "Gillan", ally2: "Azrael", ally3: "Klein"},
    {name: "Sol Badguy", property: "Rock", type: "Balance", terr1: "Lava", imgurl: "../assets/Sol_Badguy.png", id: 73, party: false, ally1: "Ky_Kiske", ally2: "May", ally3: "Ramlethal_Valentine"},
    {name: "Sonic Boom", property: "Scissors", type: "Balance", terr1: "Lava", imgurl: "../assets/Sonic_Boom.png", id: 10, party: false, ally1: "Mas", ally2: "Lena", ally3: "Nox"},
    {name: "Spooky", property: "Rock", type: "Support", terr1: "Lava", imgurl: "../assets/Spooky.png", id: 38, party: false, ally1: "Banshee", ally2: "Banshee", ally3: "Banshee"},
    {name: "Sraka", property: "Scissors", type: "Attack", terr1: "Water", imgurl: "../assets/Sraka.png", id: 11, party: false, ally1: "Alfred", ally2: "Bearman", ally3: "Lilid"},
    {name: "Taehwa", property: "Scissors", type: "Balance", terr1: "Water", imgurl: "../assets/Taehwa.png", id: 75, party: false, ally1: "Sraka", ally2: "Dolores", ally3: "Krut"},
    {name: "Tao", property: "Scissors", type: "Attack", terr1: "Thornbush", imgurl: "../assets/Tao.png", id: 35, party: false, ally1: "Alfred", ally2: "Lily", ally3: "Unknown"},
    {name: "Thanatos", property: "Rock", type: "Balance", terr1: "Poison", imgurl: "../assets/thanatos.png", id: 66, party: false, ally1: "Celestial", ally2: "Yekaterina", ally3: "Kai"},
    {name: "Unknown", property: "Rock", type: "Attack", terr1: "Water", imgurl: "../assets/Unknown.png", id: 41, party: false, ally1: "Nirvana", ally2: "Shu-Shu", ally3: "Belle"},
    {name: "Valkyrie", property: "Paper", type: "Defense", terr1: "Thornbush", imgurl: "../assets/Valkyrie.png", id: 27, party: false, ally1: "Chris", ally2: "Kai", ally3: "Alfred"},
    {name: "Yeka", property: "Rock", type: "Balance", terr1: "Water", imgurl: "../assets/Yeka.png", id: 74, party: false, ally1: "Celestial", ally2: "Yekaterina", ally3: "Carrot"},
    {name: "Zero", property: "Rock", type: "Balance", terr1: "Poison", imgurl: "../assets/Zero.png", id: 46, party: false, ally1: "Cleo", ally2: "Momo", ally3: "Sione"},
];
